### ISSUE TITLE
Badly Formatted Google Finance Data Causes Runtime Errors

### ISSUE THREAD

**Issue by jakehoskins** [gbeced/pyalgotrade#110]
The Google finance module can insert '-' instead of a float value.
This caused me to have runtime errors. I used the following command:

` python -c "from pyalgotrade.tools import googlefinance; googlefinance.download_daily_bars('orcl', 2000, 'orcl-2000.csv')"`

I got back the following (truncated for readability)

```
Date,Open,High,Low,Close,Volume
6-Oct-17,48.64,48.70,48.22,48.40,16340405
5-Oct-17,48.96,49.03,48.50,48.91,13886059
...
31-Jul-17,-,-,49.90,49.93,10066602
```

**Comment by jakehoskins** [comment]
I have a PR if you want to take a look:

https://github.com/gbeced/pyalgotrade/pull/111

**Comment by gbeced** [comment]
The problem is that if there is missing data there is not much to do. If you create bars without those values (using None instead of a price) you'll end up with undefined behaviour in different places.

**Comment by jakehoskins-yv** [comment]
Yes, I feared that would be the case. 

Could a potential fix be to pass an argument to `parseBar` to signify that you want to omit all bars that consist of a None type? This way it could just be treated as a non-trading day. I'd be interested to know your thoughts on this.

**Comment by jakehoskins** [comment]
Yes, I feared that would be the case.

Could a potential fix be to pass an optional argument to `parseBar` to signify that you want to omit all bars that consist of a None type? This way it could just be treated as a non-trading day. I'd be interested to know your thoughts on this.

**Comment by gbeced** [comment]
I fixed this here: https://github.com/gbeced/pyalgotrade/commit/b2667acae171d7abe0ad857c9fe466169c4713a0
Also, note that Google Finance API is broken. In your initial comment you requested bars for year 2000 and the file retrieved has files for year 2017
