### ISSUE TITLE
requests.exceptions.ConnectionErro  How to solve it   ???? 

### ISSUE THREAD

**Issue by Jackzhangpan** [gbeced/pyalgotrade#122]
```
from pyalgotrade.tools import yahoofinance
yahoofinance.download_daily_bars('orcl', 2000, 'orcl-2000.csv')
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ichart.finance.yahoo.com', port=80): Max retries exceeded with url: /table.csv?s=orcl&a=0&b=1&c=2000&d=11&e=31&f=2000&g=d&ignore=.csv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019566724F28>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

**Comment by gbeced** [comment]
Check this comment:
https://github.com/gbeced/pyalgotrade/issues/118#issuecomment-347066103
