### ISSUE TITLE
bitstamp sample not working on macOS High Sierra

### ISSUE THREAD

**Issue by flycjh** [gbeced/pyalgotrade#123]
macOS High Sierra, python 2.7.14
Running sample 'tutorial_bitstamp_1.py', console only shows the following output:

> 2018-05-03 18:44:30,616 bitstamp [INFO] Initializing websocket client.

**Comment by flycjh** [comment]
I found output of the sample first time has more info:

> bitstamp [INFO] Initializing websocket client.
> tornado.general [WARNING] Connect error on fd 3: [Errno 8] nodename nor servname provided, or not known

**Comment by gbeced** [comment]
Could you please give it a try with the latest version in the develop branch ? I fixed websocket clients that were not working with newer version of tornado.

**Comment by flycjh** [comment]
Thx, that works fine!
