### ISSUE TITLE
Question: strategy.getResult. What exactly does it do?

### ISSUE THREAD

**Issue by kamilww** [gbeced/pyalgotrade#164]
Hi everyone,

New to Pyalgotrade, so sorry if this is a dumb question. I'm having trouble understanding how getResult is calculating backtest results.

When analyzing my backtest, using the following:
print("Final portfolio value: $%.2f" % strategy.getResult())
print("getLastPrice: $%.2f" % strategy.getLastPrice("spy"))
print("getShares: %.2f" % strategy.position.getShares())
print("Cumulative returns: %.2f %%" % (returnsAnalyzer.getCumulativeReturns()[-1] * 100))
print("Max. drawdown: %.2f %%" % (drawDownAnalyzer.getMaxDrawDown() * 100))
print("Longest drawdown duration: %s" % (drawDownAnalyzer.getLongestDrawDownDuration()))

I am provided with the following:
Final portfolio value: $3060228.61
getLastPrice: $435.52
getShares: 6923.00
Cumulative returns: 206.02 %
Max. drawdown: 21.76 %
Longest drawdown duration: 802 days, 0:00:00

Now, $435.52 * 6923 equals 3,015,104.96 and not 3,060,228.61. What parameters is getResult using to calculate its results?

**Comment by gbeced** [comment]
Email list should be used to questions, not GitHub issues.
