### ISSUE TITLE
Remove methods .get and .set

### ISSUE THREAD

**Issue by SlyOne** [gbeced/pyalgotrade#18]
Hey:

Restarted working on this again and using the .getXXX and .setXXX getting in the way of sorts. Are you planning or were you considering removing the method leader of "get" and "set." Its not pythonic, its more java-ish...

Using snippets from tutorial:
Now:
    def onStart(self):
        print "Initial portfolio value: $%.2f" % self.getBroker().getEquity()

New could be: 
 def onStart(self):
        print "Initial portfolio value: $%.2f" % self.broker().equity()

Now:
    def onEnterOk(self, position):
        execInfo = position.getEntryOrder().getExecutionInfo()
        print "%s: BUY  at $%.2f" % (execInfo.getDateTime(), execInfo.getPrice())

New could be:
    def onEnterOk(self, position):
        execInfo = position.entryOrder().executionInfo()
        print "%s: BUY  at $%.2f" % (execInfo.dateTime(), execInfo.price())

A way to accomlish this would be: to create new 'defs' in the current classes with the shorten names. and then wrapper orginal functions.

or better yet. Create new def's with shorter names then call new 
function with old name.

Example

def richQuick(parms);
     'do something that makes money'

def getRichQuick(parms):
      richQuick(parms)
      print 'Future Waring: get and set methods will be deprecated soon use shorter names''

What do you think??

**Comment by disconnect3d** [comment]
+1

@gbeced would be nice if you start taking into account issues.

**Comment by tibkiss** [comment]
@disconnect3d : This is not an issue, but a feature request.
You are welcome to create a pull request and the owner can decide to merge it or not.

**Comment by gbeced** [comment]
It would be nice if your mom blows me.
