### ISSUE TITLE
Options Trading

### ISSUE THREAD

**Issue by sanalpanakkat** [gbeced/pyalgotrade#181]
Does anyone developed an backtesting for options trading using pyalgotrade?
If anyone know to do the backtesting with any other library or pyalgotrade, Please help me ..

Thank you

**Comment by gbeced** [comment]
This project is deprecated and is no longer mantained. You may be interested in taking a look at [Basana](https://github.com/gbeced/basana).

**Comment by sanalpanakkat** [comment]
I am not asking to maintain the project. Just asking can i develop options trading in pyalgotrade using custom functions ? Is it possible or not?
