### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by femtotrader** [gbeced/pyalgotrade#42]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with pyalgotrade. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable pyalgotrade on @Sourcegraph by going to https://sourcegraph.com/github.com/gbeced/pyalgotrade and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by gbeced** [comment]
Done.

**Comment by gbeced** [comment]
Builds are failing. Do you know what is going on ?
https://sourcegraph.com/github.com/gbeced/pyalgotrade/.builds

**Comment by femtotrader** [comment]
That's maybe a problem in srclib https://srclib.org/ so I've just submit this issue as https://github.com/sourcegraph/sourcegraph.com/issues/357
