### ISSUE TITLE
Python 2 to 3 Errors with Proposed Fixes (Getting Started) 

### ISSUE THREAD

**Issue by drshrey** [gbeced/pyalgotrade#45]
Just did the getting started tutorial, and here are the errors that I got because of using Python 3. Unless I'm using the 2to3 tool wrong, there may be a few syntactic issues in the code (for Python 3 atleast).
tools/yahoofinance.py: 

**Line 21:**
Current: `import urllib2`
Error: urllib2 module cannot be found
Reason: Since I'm using Python 3, urllib2 is no apart of urllib, and urllib is split up into different modules, specifically urllib.request and urllib.errors.
My change: `import urllib.request as urllib2`

**Line 130:**
Current:`except Exception, e`
Error: invalid syntax
Reason: Python 3 semantics
My change: `except Exception as e`

**Line 48:**
Current: `while not buff[0].isalnum()`
Error: 'int' object does not have attribute isalnum()
Reason: isalnum() is only applicable to strings.
My change: `while not str(buff[0]).isalbum()`

**Line 67:** 
Current: `f.write(bars)`
Error: TypeError: must be str, not bytes
Reason: See error
My change: `f.write(str(bars))`

After that compiled, I went over to the actual strategy code. Here's my list of changes to the errors received:

**utils/csvutils.py**

line 30: 
Current: `self.__fieldNames = self.reader.next()`
Error: AttributeError: '_csv.reader' object has no attribute 'next'
Reason: Python 3 changes
My change: ```self.__fieldNames  = next(self.reader())

More to come later...

**Comment by drshrey** [comment]
It compiles after this error and outputs the correct csv file, just to confirm.

**Comment by gbeced** [comment]
Thanks a lot, but I won't be working in porting PyAlgoTrade to Python 3 in the short term.

**Comment by femtotrader** [comment]
Python 3 is becoming more and more popular.
Six can help https://pythonhosted.org/six/
You can use Anaconda Python to have both Python 2 and Python 3
see http://continuum.io/blog/anaconda-python-3

**Comment by GaryVe** [comment]
Thanks drshrey - your input above was very useful. Just to correct the obvious: isalbum()  should be isalnum()

I also couldn't get the next(self.reader()) - or should that be next(self.reader)? - to work. Still gives me the same _csv.reader' object has no attribute 'next' error.

Any ideas?

**Comment by seedds** [comment]
With python 3.4.4 and 2to3.py, only the following changes should be made to make pyalgotrade python3 compatible

yahoofinance.py:
My change: 
line 44:
from:
buff = f.read()
to:
buff = f.read().decode('utf-8')

barfeed/membf.py:
line 70-71:
from:
barCmp = lambda x, y: cmp(x.getDateTime(), y.getDateTime())
self.__bars[instrument].sort(barCmp)
to:
barCmp = lambda x: x.getDateTime()
self.__bars[instrument].sort(key=barCmp)

**Comment by fccoelho** [comment]
The modernize library is also of great help migrating codebases from Python 2 to Python 3
Maybe someone could make their fork, Python 3 compatible and announce it here.

**Comment by drshrey** [comment]
I'll see what I can do this weekend, I'm going to try my hand at a Fabfile, so all you'd have to do is a fab init and you'd be good to go with pyalgotrade. Thoughts?

**Comment by shev72** [comment]
drshey:  your work is really helpful , can you fork and update with your changes?  I am happy also to contribute fixes toward py3 compatibility.

**Comment by kennell** [comment]
Hey folks. It seems i am a bit late to the party, but i would also offer my help in creating and maintaining a py3-compatible branch.

**Comment by AdrianP-** [comment]
I did this change with python 3.5:  `self.__fieldNames = next(self.reader())` but I got `TypeError: '_csv.reader' object is not callable`
And changed it with next(self.reader), `TypeError: '_csv.reader' object is not callable`

There are some fork with python3 compatible? Thanks

**Comment by alsilva86** [comment]
Really helpful drshrey! I'm getting this error when trying to run a basic strategy from the PyAlgo tutorial:

ImportError: No module named 'slippage'

Can you please advise about whats going on ?

**Comment by LimingFang** [comment]
my problem is that when trying to run a basic strategy from the PyAlgo tutorial:

ImportError: No module named 'slippage'

**Comment by josebagar** [comment]
@alsilva86 @LimingFang 
In order to avoid the ImportError with slippage, you can change pyalgotrade/broker/fillstrategy.py:25 from:
`import slippage`
to
`import pyalgotrade.broker.slippage`.

If you're following the PyAlgoTrade tutorial, you'll probably then get the problem described by @AdrianP- .

**Comment by suuuch** [comment]
Is there any schedule to develop Py3 version ?
Or 
Is there any  volunteer to do this ?

**Comment by chownc** [comment]
I read through all of the very useful comments above then discovered someone has recently created a port for Python 3.6.  Thought you might find this useful - https://github.com/chenlocus/pyalgotrade-python-3

**Comment by gbeced** [comment]
I'm working on supporting both Python2.7 and Python3 in feature/python3.
