### ISSUE TITLE
Runtime Warnings from matplotlib in SMA crossover sample 

### ISSUE THREAD

**Issue by MatthiasKauer** [gbeced/pyalgotrade#46]
Hi,
I started experimenting with pyalgotrade today. I used the SMA crossover strategy sample posted here: http://gbeced.github.io/pyalgotrade/docs/v0.16/html/sample_sma_crossover.html
I added a ```print pyalgotrade.__version__ ```(the 0.16 output below).
Plots are similar to your web site on my end. I receive the following RuntimeWarning however and I am therefore wondering what I am doing wrong?

My guess is that data is missing in the early periods of the MA. 
For reference, this is a Win7 PC with python 2.7.

Best regards,
Matthias

    C:\dvl\pybacktest_comparison>python pyalgo_sample.py
    0.16
    Sharpe ratio: 1.12
    C:\Anaconda\lib\site-packages\matplotlib\transforms.py:644: RuntimeWarning: invalid value encountered in sign
      dx0 = np.sign(vertices[:, 0] - x0)
    C:\Anaconda\lib\site-packages\matplotlib\transforms.py:645: RuntimeWarning: invalid value encountered in sign
      dy0 = np.sign(vertices[:, 1] - y0)
    C:\Anaconda\lib\site-packages\matplotlib\transforms.py:646: RuntimeWarning: invalid value encountered in sign
      dx1 = np.sign(vertices[:, 0] - x1)
    C:\Anaconda\lib\site-packages\matplotlib\transforms.py:647: RuntimeWarning: invalid value encountered in sign
      dy1 = np.sign(vertices[:, 1] - y1)

**Comment by gbeced** [comment]
Which versions of Numpy and Matplotlib are you using ?

**Comment by MatthiasKauer** [comment]
interestingly, these warning don't appear on my debian machine where

```
>>> import matplotlib
>>> matplotlib.__version__
'1.4.2'
>>> import numpy
>>> numpy.__version__
'1.8.2'
```

I'll check on Windows again later :)

**Comment by MatthiasKauer** [comment]
On Windows:

```
Python 2.7.6 |Anaconda 1.9.2 (32-bit)| (default, Nov 11 2013, 10:50:31) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.8.1'
>>> import matplotlib
>>> matplotlib.__version__
'1.3.1'
>>>
```

**Comment by gbeced** [comment]
Did you try upgrading matplotlib on Windows to see if that warning
disappears ?

**Comment by MatthiasKauer** [comment]
no, I hadn't.
And interestingly, yes it does. (on numpy 1.9.2 and matplotlib 1.4.now after conda update matplotlib)
