### ISSUE TITLE
Forex Example

### ISSUE THREAD

**Issue by crazy25000** [gbeced/pyalgotrade#54]
Would you also post sample code, CSV to test currency strategy?

**Comment by gbeced** [comment]
I don't know what is this. Submit questions to the forums, and spend a couple of minutes trying to write something that can be understood.

**Comment by crazy25000** [comment]
Hey, 

Sorry about that, here is what I tried, but kept getting errors: re-wrote the tutorial example to use a local CSV using the CSV class instead of the yahoo:

Original:
def run_strategy(smaPeriod):
    # Load the yahoo feed from the CSV file
    feed = yahoofeed.Feed()
    feed.addBarsFromCSV("orcl", "orcl-2000.csv")

    # Evaluate the strategy with the feed.
    myStrategy = MyStrategy(feed, "orcl", smaPeriod)
    myStrategy.run()
    print "Final portfolio value: $%.2f" % myStrategy.getBroker().getEquity()

run_strategy(15)

Modified:
def run_strategy(smaPeriod):
    feed = csvfeed.Feed("Date", "%m-%d-%Y")
    feed.addValuesFromCSV("eur_usd.csv")

    # Evaluate the strategy with the feed.
    myStrategy = MyStrategy(feed, smaPeriod)
    myStrategy.run()
    print "Final portfolio value: $%.2f" % myStrategy.getBroker().getEquity()

run_strategy(15)

The eur_usd.csv contains:
Time,Open,High,Low,Close
01.01.2013,1.32259,1.32261,1.32259,1.32261
01.02.2013,1.32261,1.32261,1.32261,1.32261
01.03.2013,1.32262,1.32303,1.32262,1.32303

I can re-write the date to match any format and I just want to use this library for testing local CSV files for Forex pairs. If you still want me to move this to a forum, is there one for this?

Thanks,

**Comment by crazy25000** [comment]
Also changed Time to Date in the CSV*

**Comment by gbeced** [comment]
What is the error that you get ?

**Comment by crazy25000** [comment]
With the below code I get an error because the strategy class requires an instrument:

    def run_strategy(smaPeriod):
        feed = csvfeed.Feed("Date", "%m.%d.%Y")
        feed.addValuesFromCSV("eur_usd.csv")

        myStrategy = MyStrategy(feed, smaPeriod)
        myStrategy.run()
        print "Final portfolio value: $%.2f" % myStrategy.getBroker().getEquity()

    run_strategy(15)

This is the beginning of the default strategy class in the tutorial:

    class MyStrategy(strategy.BacktestingStrategy):
        def __init__(self, feed, instrument, smaPeriod):
            strategy.BacktestingStrategy.__init__(self, feed, 1000)

If I add EURGBP to be used as an instrument, it gives a key error:

    def run_strategy(smaPeriod):
        feed = csvfeed.Feed("Date", "%m.%d.%Y")
        feed.addValuesFromCSV("eur_usd.csv")

        myStrategy = MyStrategy(feed, smaPeriod)
        myStrategy.run()
        print "Final portfolio value: $%.2f" % myStrategy.getBroker().getEquity()

    run_strategy(15)

#####    self.__sma = ma.SMA(feed[instrument].getPriceDataSeries(), smaPeriod)
#####  File "/usr/lib/python2.7/site-packages/pyalgotrade/feed/__init__.py", line 113, in __getitem__
#####    return self.__ds[key]
##### KeyError: 'EURGBP'

I also tried removing instrument as a requirement for the strategy class, but got a different error.

**Comment by crazy25000** [comment]
Here is the full code, figured it would be easier to debug. I think the error is because I'm not sure how to modify the strategy class to fit the CSV class  instead of the Yahoo class:

    from pyalgotrade import strategy
    from pyalgotrade.feed import csvfeed
    from pyalgotrade.technical import ma


    class MyStrategy(strategy.BacktestingStrategy):
        def __init__(self, feed, instrument, smaPeriod):
            strategy.BacktestingStrategy.__init__(self, feed, 1000)
            self.__position = None
            self.__instrument = instrument
            # We'll use adjusted close values instead of regular close values.
            # self.setUseAdjustedValues(False)
            self.__sma = ma.SMA(feed[instrument].getPriceDataSeries(), smaPeriod)

        def onEnterOk(self, position):
            execInfo = position.getEntryOrder().getExecutionInfo()
            self.info("BUY at $%.2f" % (execInfo.getPrice()))

        def onEnterCanceled(self, position):
            self.__position = None

        def onExitOk(self, position):
            execInfo = position.getExitOrder().getExecutionInfo()
            self.info("SELL at $%.2f" % (execInfo.getPrice()))
            self.__position = None

        def onExitCanceled(self, position):
            # If the exit was canceled, re-submit it.
            self.__position.exitMarket()

        def onBars(self, bars):
            # Wait for enough bars to be available to calculate a SMA.
            if self.__sma[-1] is None:
                return

            bar = bars[self.__instrument]
            # If a position was not opened, check if we should enter a long position.
            if self.__position is None:
                if bar.getPrice() > self.__sma[-1]:
                    # Enter a buy market order for 10 shares. The order is good till canceled.
                    self.__position = self.enterLong(self.__instrument, 10, True)
            # Check if we have to exit the position.
            elif bar.getPrice() < self.__sma[-1] and not self.__position.exitActive():
                self.__position.exitMarket()


    def run_strategy(smaPeriod):
        feed = csvfeed.Feed("Date", "%m.%d.%Y")
        feed.addValuesFromCSV("eur_usd.csv")

        # Evaluate the strategy with the feed.
        myStrategy = MyStrategy(feed, 'EURGBP', smaPeriod)
        myStrategy.run()
        print "Final portfolio value: $%.2f" % myStrategy.getBroker().getEquity()

    run_strategy(20)
