### ISSUE TITLE
longest drawdown duration

### ISSUE THREAD

**Issue by thereheis** [gbeced/pyalgotrade#55]
I found that in  sample-strategy-analyzer.output:  Longest drawdown duration: 277 days, 0:00:00, but the data is just within 1 year, is there anything wrong or I just misunderstood the define of longest drawdown duration? Thanks.

**Comment by gbeced** [comment]
Why do you think there is anything wrong with that ? Did you try plotting ?

**Comment by joshua-xue** [comment]
I plot the portfolio return, it's right , thanks
