### ISSUE TITLE
StochasticOscillator ZeroDivisionError

### ISSUE THREAD

**Issue by blakejennings** [gbeced/pyalgotrade#61]
If ```highestHigh``` equals ```lowestLow```, the line referenced below will throw a ```ZeroDivisonError``` when populating the DataSeries. I am happy to submit a pull request, wrapping this line in a try/catch, but wanted to ask what you would prefer the return value to be in this situation, or if you'd like to handle this in some other way. 

Thanks! 
 
https://github.com/gbeced/pyalgotrade/blob/master/pyalgotrade/technical/stoch.py#L63

**Comment by gbeced** [comment]
I believe that in that case (currentClose - lowestLow) would also be zero, so the function should return zero. Check the fix in https://github.com/gbeced/pyalgotrade/commit/5331a28fa94670a6bc0b14f1a37e2f6961df38d4
Thanks for the bug report.
