### ISSUE TITLE
Docstring for `Returns` class suggests that it has infinite length

### ISSUE THREAD

**Issue by disconnect3d** [gbeced/pyalgotrade#62]
Currently, `Returns` docstring suggests that the net/cumulative returns returned by it has infinite length:

```python
class Returns(stratanalyzer.StrategyAnalyzer):
    """A :class:`pyalgotrade.stratanalyzer.StrategyAnalyzer` that calculates
    time-weighted returns for the whole portfolio."""

    def __init__(self):
        self.__netReturns = dataseries.SequenceDataSeries()
        self.__cumReturns = dataseries.SequenceDataSeries()
```

Either it should be stated there, that the maximum length can be changed and have a default value or let it be infinite by default.

I would vote for the second solution.

**Comment by physicsd00d** [comment]
I think 2abd8d19 closes this issue.

**Comment by disconnect3d** [comment]
Thanks @physicsd00d, I am closing the issue.
