### ISSUE TITLE
self.getBroker().getCash() does not report partial-fills properly

### ISSUE THREAD

**Issue by adsar** [gbeced/pyalgotrade#65]
I found this problem in the BacktestingStrategy class:

After entering a market sell order, the framework executes a partial sell:
if you call  self.getBroker().getCash() from onExitOk() it will report a total as if the order was already fully executed.

The expected balance should be:
previous balance + position.getEntryOrder().getExecutionInfo().getQuantity() \* .getExecutionInfo().getPrice()  (the amount of the partial sell)

**Comment by gbeced** [comment]
If onExitOk gets called then the position is completely closed. Could you provide an example that reproduces the issue ?
Thanks

**Comment by pjz** [comment]
> The expected balance should be:
> `previous balance + position.getEntryOrder().getExecutionInfo().getQuantity() * .getExecutionInfo().getPrice()` (the amount of the partial sell)

I think your expectation is wrong, because market orders can fill at more than one price.   You should expect to get something more like: `previous balance + position.getEntryOrder().getQuantity() * position.getEntryOrder().getAvgFillPrice()`

**Comment by gbeced** [comment]
I should have elaborated a bit more. If you submit an exit order via the position interface, that order may get X partial fills, and a final one when the order gets completely filled. onExitOk will ONLY get called on the final one when the order is completely filled.
