### ISSUE TITLE
Local optimization not working

### ISSUE THREAD

**Issue by eviltnan** [gbeced/pyalgotrade#66]
After starting the local optimizer the process freezing while waiting workers (???).

> 2016-02-25 22:32:01,523 server [INFO] Loading bars
> 2016-02-25 22:32:03,232 server [INFO] Waiting for workers

If you explicitly set worker numbers, something happens, but not all parameters combinations are processed

**Comment by eviltnan** [comment]
This happens if run() method raises an exception, which is quite bad, because you won't have a possibility to control that. The worker should stop and notify the server, that the process couldn't be finished.

**Comment by gbeced** [comment]
Thanks for the bug report.
I'd recommend you to add exception handling to your strategies anyway.
