### ISSUE TITLE
Access previous bars from the onBars function

### ISSUE THREAD

**Issue by ximo1984** [gbeced/pyalgotrade#70]
def onBars(self, bars):
  pass

In this function how to get previous bars? You can only access to the current bar.

**Comment by ximo1984** [comment]
Perhaps this works:

def _get_previous_bar(self, inst):
        previous_bar = None

        try:
            previous_bar = self.getFeed().getDataSeries(inst)[-2]
        except IndexError:
            pass

        return previous_bar

**Comment by gbeced** [comment]
Don't just open an issue just to ask a question. There is an email list to ask questions.
