### ISSUE TITLE
any way to add new bar feeds when trading?

### ISSUE THREAD

**Issue by maxsonic** [gbeced/pyalgotrade#72]
Hi,

I would like to change my portfolio when trading, say, I have added two instruments on day 1 and I want to add another two instruments and remove 1 instruments on one day 3. Is there any way to do it? Since I have thousand instruments to trade from 2000 to 2016. It would be impossible to add all  the bars into the strategy at the beginning.

I tried to edit the code, but found that the bar got the same date called twice sometime. Can you point out the places where I should modify?

**Comment by gbeced** [comment]
This is not an issue. Please use the forum.

**Comment by maxsonic** [comment]
I have searched for a while in the forum, but found no result... Should the keyword be "multiple instrument", "switch portfolio".
I am sorry that I am not a native English speaker and don't know the exact words for the investment business.
