### ISSUE TITLE
Run Optimiser on desktop, default defaultBatchSize

### ISSUE THREAD

**Issue by lyastro** [gbeced/pyalgotrade#73]
Hi @gbeced ,

Thanks for this excellent python tool. 
It is performs very good and helps me a lot.
But I met a problem when I first use the optimiser module on my desktop following the example in http://gbeced.github.io/pyalgotrade/docs/v0.17/html/tutorial.html

It was strange to me that only 1/200 sets of parameter could be run with the optimiser. 
And I looked into the code and found that the default `defaultBatchSize = 200`, which lead to the issue that I met.

It would be better to add some description or reminder about this parameter in http://gbeced.github.io/pyalgotrade/docs/v0.17/html/tutorial.html, where all the beginner starts from.

And it is better to add `pyalgotrade.optimizer.server.Server.defaultBatchSize=1` in local.py.

Cheers,
lyastro

**Comment by gbeced** [comment]
Hi, please don't use GitHub issues to ask questions. Use the email list instead.
Your understanding of defaultBatchSize is not correct. The workers don't receive each parameter combination one at a time and report results on each one of them. The receive 200 parameter combinations (the batch) and the report back the best of those. They work on 200 parameter combinations at a time.
