### ISSUE TITLE
How to trade with current bar's price

### ISSUE THREAD

**Issue by fanchangyong** [gbeced/pyalgotrade#77]
This is a great project, but I've encountered some problem:
According to this code: 
https://github.com/gbeced/pyalgotrade/blob/master/pyalgotrade/strategy/__init__.py#L578, 
there's a comment:
```
# The broker should subscribe to barFeed events before the strategy.
# This is to avoid executing orders submitted in the current tick.
```
in some situations, I want the trade made in the `current` bar's price,
but it seems that under the current mechanism, I can only trade with the next bar's open price or close price.
How could I trade with current bar's open or close or other price?
Thank you!

**Comment by gbeced** [comment]
Use the group for questions.
