### ISSUE TITLE
Support reinvesting short profits

### ISSUE THREAD

**Issue by jasonmellone** [gbeced/pyalgotrade#80]
Hello

As short positions are marked to market, cash is made available in an account, and the investor is allowed to short additional shares "on the way down" (as one might say) as to establish a larger position using profits from initial position.

Example:
T=0, short 100 share of XYZ priced at $100.
T=1,  XYZ declines $10 to $90, yielding $1,000 of profit. Take $1,000 of profit and short an additional 11 shares.

There should be a flag of "reinvest short gains".

If not you are requiring a synthetic position to be closed and reopened at each interval, which is quite messy.

**Comment by gbeced** [comment]
There is something that I don't understand. How do you get those $1000 profit without actually closing the short position ? At T=1 you only have unrealized profit if you don't close the position.

**Comment by jasonmellone** [comment]
Thanks for the response. This gets into specifics of brokers, but for example:

Fidelity marks shorts to market every Thursday (why Thursday? no clue). The profit (ignoring losses for the time being) you have can then be reinvested (short more shares etc). With this, as the short "performs" you can short additional shares.

This is further true with futures contracts (which you support easily, but just behave a bit differently as they are derivatives). Example being daily mark to market of futures contracts.

Unsure if this is out of scope for this project or not.

I need to wrap my head around how the problem should be expressed, but I am happy to contribute if I feel I can make a material impact.

**Comment by gbeced** [comment]
Jason, I won't working on this for two reasons:
* It seems to be specific to one broker.
* I still don't understand how you can get the profit without actually closing the position. I mean, don't get get fees deduced from your profit re-entering a bigger short position ?
