### ISSUE TITLE
What does SMA mean when using Frequency.TRADE？

### ISSUE THREAD

**Issue by ericyue** [gbeced/pyalgotrade#82]
I'm confused about sample code in http://gbeced.github.io/pyalgotrade/docs/v0.18/html/bitstamp_example.html

usually, when I use Frequency.DAY and SMA(10) it means 10 days average price. 
What does SMA(10) mean when using Frequency.TRADE？

and how to use daily SMA in a barfeed with Frequency.TRADE?

**Comment by pjz** [comment]
Frequency.TRADE means you get each trade tick individually, as it happens.

**Comment by ericyue** [comment]
@pjz   thanks for reply.   so you means that when using Frequency.TRADE with SMA(10), it means 10-trades-average price ?  how to convert to minute or daily price when live trade ?

**Comment by pjz** [comment]
That is what I mean.  And as I also said, you'll need to resample it to get a minute or daily price.  I think there's code in https://github.com/gbeced/pyalgotrade/blob/master/pyalgotrade/barfeed/resampled.py to do that.

**Comment by ericyue** [comment]
@pjz   yes , but as i understand ,resample method cannot be used in live-trade or paper-trade in TRADE FREQUENCY.

**Comment by ericyue** [comment]
@pjz  thks, I will try some way else.

**Comment by gbeced** [comment]
Please don't use Github issues for this. Use the google group instead.
If your main barfeed has trade frequency you can use this: http://gbeced.github.io/pyalgotrade/docs/v0.18/html/strategy.html#pyalgotrade.strategy.BaseStrategy.resampleBarFeed and it should work for realtime feeds as well.
