### ISSUE TITLE
I can't set two exits for one filled position

### ISSUE THREAD

**Issue by adrian-chang-alcover** [gbeced/pyalgotrade#90]
Hi people.
I enter long and then I want two exits for this filled position, one for make profit and another to stop loss.
```
self.long = self.enterLongStop(self.instrument, self.high, self.quantity)
if self.long and self.long.entryFilled() and not self.long.exitActive():
            self.long.exitLimit(self.high + 1)
            self.long.exitStop(self.high` - 1)
```
but I get:
`Exception: Exit order is active and it should be canceled first`

How can I get this approach? Thanks

**Comment by gbeced** [comment]
Use the google group to ask questions.
