### ISSUE TITLE
not able to install using anaconda

### ISSUE THREAD

**Issue by arshpreetsingh** [gbeced/pyalgotrade#91]
Hi, I am not able to install pyalgotrade using anconda on linux. Can you make pyalgotrade available using Anaconda?

**Comment by kfpotts1** [comment]
Use command line command "source activate your_conda_env_here" then once the environment is active you can run "pip install pyalgotrade" and it will install the package to your specified anaconda environment.

**Comment by arshpreetsingh** [comment]
Thanks, It was very helpful.

**Comment by gbeced** [comment]
Please use the google group to ask questions.
